apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-world
  labels:
    app: flask-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hello-world
  template:
    metadata:
      labels:
        app: flask-hello-world
    spec:
      containers:
      - name: flask-hello-world
        image: acrweb2b.azurecr.io/hello_world:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: flask-hello-world-service
spec:
  type: LoadBalancer
  selector:
    app: flask-hello-world
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000