---
    - name: Task - 1 Update APT package manager repositories cache
      apt:
        update_cache: yes

    - name: Task -2 Install Java using Ansible
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - openjdk-17-jdk

